codecov:
  require_ci_to_pass: yes

ignore:
  - "app/Http/Controllers/Auth"
  - "app/Http/Controllers/HomeController.php"
  - "app/Http/Middleware/Authenticate.php"
  - "app/Http/Middleware/CheckForMaintenanceMode.php"
  - "app/Http/Middleware/EncryptCookies.php"
  - "app/Http/Middleware/RedirectIfAuthenticated.php"
  - "app/Http/Middleware/TrimStrings.php"
  - "app/Http/Middleware/TrustHosts.php"
  - "app/Http/Middleware/TrustProxies.php"
  - "app/Http/Middleware/VerifyCsrfToken.php"
